/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author leticia.mourao
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
         setLocationRelativeTo(null);
          setTitle("PlugVendas - Menu Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bttCliente = new javax.swing.JButton();
        bttProdutos = new javax.swing.JButton();
        bttFornecedores = new javax.swing.JButton();
        bttPedidos = new javax.swing.JButton();
        bttMinhasVendas = new javax.swing.JButton();
        bttVender = new javax.swing.JButton();
        bttRelatorio = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MENU");

        bttCliente.setBackground(new java.awt.Color(0, 0, 0));
        bttCliente.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bttCliente.setForeground(new java.awt.Color(255, 255, 255));
        bttCliente.setText("Clientes");
        bttCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttClienteActionPerformed(evt);
            }
        });

        bttProdutos.setBackground(new java.awt.Color(0, 0, 0));
        bttProdutos.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bttProdutos.setForeground(new java.awt.Color(255, 255, 255));
        bttProdutos.setText("Produtos");
        bttProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttProdutosActionPerformed(evt);
            }
        });

        bttFornecedores.setBackground(new java.awt.Color(0, 0, 0));
        bttFornecedores.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bttFornecedores.setForeground(new java.awt.Color(255, 255, 255));
        bttFornecedores.setText("Fornecedores");
        bttFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttFornecedoresActionPerformed(evt);
            }
        });

        bttPedidos.setBackground(new java.awt.Color(0, 0, 0));
        bttPedidos.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bttPedidos.setForeground(new java.awt.Color(255, 255, 255));
        bttPedidos.setText("Pedidos");
        bttPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPedidosActionPerformed(evt);
            }
        });

        bttMinhasVendas.setBackground(new java.awt.Color(0, 0, 0));
        bttMinhasVendas.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bttMinhasVendas.setForeground(new java.awt.Color(255, 255, 255));
        bttMinhasVendas.setText("Minhas Vendas");
        bttMinhasVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMinhasVendasActionPerformed(evt);
            }
        });

        bttVender.setBackground(new java.awt.Color(0, 0, 0));
        bttVender.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        bttVender.setForeground(new java.awt.Color(255, 255, 255));
        bttVender.setText("Vender");
        bttVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVenderActionPerformed(evt);
            }
        });

        bttRelatorio.setBackground(new java.awt.Color(0, 0, 0));
        bttRelatorio.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        bttRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        bttRelatorio.setText("Relatorio");
        bttRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRelatorioActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Sair");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/PlugVendasLogo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttVender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bttProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttMinhasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                            .addComponent(bttRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton8))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bttCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttFornecedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttMinhasVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttVender)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPedidosActionPerformed
   
    TelaPedidos tela = new TelaPedidos();
    tela.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_bttPedidosActionPerformed

    private void bttClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClienteActionPerformed
    TelaCliente tela = new TelaCliente();
    tela.setVisible(true);
    this.dispose();        
        
    }//GEN-LAST:event_bttClienteActionPerformed

    private void bttProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttProdutosActionPerformed
    TelaProdutos tela = new TelaProdutos();
    tela.setVisible(true);
    this.dispose();    }//GEN-LAST:event_bttProdutosActionPerformed

    private void bttFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttFornecedoresActionPerformed
    TelaFornecedores tela = new TelaFornecedores();
    tela.setVisible(true);
    this.dispose();
        
        
    }//GEN-LAST:event_bttFornecedoresActionPerformed

    private void bttRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRelatorioActionPerformed
     
    TelaRelatorio tela = new TelaRelatorio();
    tela.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_bttRelatorioActionPerformed

    private void bttMinhasVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMinhasVendasActionPerformed

    TelaMinhasVendas tela = new TelaMinhasVendas();
    tela.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_bttMinhasVendasActionPerformed

    private void bttVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVenderActionPerformed
       
        TelaVender tela = new TelaVender();
    tela.setVisible(true);
    this.dispose();
        
    }//GEN-LAST:event_bttVenderActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCliente;
    private javax.swing.JButton bttFornecedores;
    private javax.swing.JButton bttMinhasVendas;
    private javax.swing.JButton bttPedidos;
    private javax.swing.JButton bttProdutos;
    private javax.swing.JButton bttRelatorio;
    private javax.swing.JButton bttVender;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
